"""empty message

Revision ID: 01abfcd653a8
Revises: 
Create Date: 2019-09-04 18:50:29.029214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01abfcd653a8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.Column('password', sa.String(length=20), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.Column('createdAt', sa.String(length=30), nullable=True),
    sa.Column('updatedAt', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
